sudo: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
matrix:
  include:
    - language: node_js
      node_js:
        - "11"
      install:
        - yarn --cwd "backend" install
      script:
        - yarn --cwd "backend" run build
        - yarn --cwd "backend" run test
    - language: node_js
      node_js:
        - "11"
      install:
        - yarn --cwd "frontend" install
      script:
        - yarn --cwd "frontend" run build
        - yarn --cwd "frontend" run test