matrix:
  include:
    - language: node_js
      install:
          - yarn --cwd "backend"
          - yarn --cwd "frontend"
      script:
          - yarn --cwd "backend" run build
          - yarn --cwd "frontend" run build
    - language: go
      go:
        - "1.11"
      env:
        - GO111MODULE=on
      install:
        - go mod download
      script:
        - go build cmd/backend/main.go