version: '3'
services:
  postgres:
    container_name: "PostgreSQL-database"
    image: "postgres:10.5-alpine"
    ports:
      - "5432:5432"
  backend:
    container_name: "Backend"
    links:
      - postgres
    build:
      context: backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres@postgres/postgres
  frontend:
    container_name: "Frontend"
    build:
      dockerfile: Dockerfile.dev
      context: frontend
      args:
        - NODE_ENV=development
    command: yarn
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=development