version: '3'
services:
  postgres:
    container_name: "PostgreSQL-database"
    image: "postgres:10.5-alpine"
    ports:
      - "5432:5432"
  backend:
    container_name: "Backend"
    links:
      - postgres
    build:
      context: backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres@postgres/postgres
  frontend:
    container_name: "Frontend"
    links:
      - backend
    build:
      dockerfile: Dockerfile
      context: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production