version: "3"
services: 
  redis:
    container_name: "redis"
    image: "redis:5.0.1-alpine"
    ports:
      - "6379:6379"
  postgres:
    container_name: "PostgreSQL-database"
    image: "postgres:10.5-alpine"
    ports:
      - "5432:5432"